[bunny]
fetch.git = "https://github.com/stelcodes/bunny.yazi"
src.git = "https://github.com/stelcodes/bunny.yazi"

[custom-shell]
fetch.git = "https://github.com/AnirudhG07/custom-shell.yazi"
src.git = "https://github.com/AnirudhG07/custom-shell.yazi"

[hover-after-moved]
fetch.git = "https://github.com/boydaihungst/hover-after-moved.yazi"
src.git = "https://github.com/boydaihungst/hover-after-moved.yazi"

[mediainfo]
fetch.git = "https://github.com/boydaihungst/mediainfo.yazi"
src.git = "https://github.com/boydaihungst/mediainfo.yazi"

[office]
fetch.git = "https://github.com/macydnah/office.yazi"
src.git = "https://github.com/macydnah/office.yazi"

[official-plugins-monorepo]
fetch.git = "https://github.com/yazi-rs/plugins"
src.git = "https://github.com/yazi-rs/plugins"

[other-monorepo]
fetch.git = "https://github.com/lpanebr/yazi-plugins"
src.git = "https://github.com/lpanebr/yazi-plugins"

[ouch]
fetch.git = "https://github.com/ndtoan96/ouch.yazi"
src.git = "https://github.com/ndtoan96/ouch.yazi"

[restore]
fetch.git = "https://github.com/boydaihungst/restore.yazi"
src.git = "https://github.com/boydaihungst/restore.yazi"

[starship]
fetch.git = "https://github.com/Rolv-Apneseth/starship.yazi"
src.git = "https://github.com/Rolv-Apneseth/starship.yazi"

[what-size]
fetch.git = "https://github.com/pirafrank/what-size.yazi"
src.git = "https://github.com/pirafrank/what-size.yazi"
