# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  bunny = {
    pname = "bunny";
    version = "bd8a767220e606f2c68c7ea7d67d1c0b97b7daf3";
    src = fetchgit {
      url = "https://github.com/stelcodes/bunny.yazi";
      rev = "bd8a767220e606f2c68c7ea7d67d1c0b97b7daf3";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mdVCZMvoe9agrnX7aZeGf0oXGffE2Fhk9f1JNbir8+Q=";
    };
    date = "2025-07-09";
  };
  custom-shell = {
    pname = "custom-shell";
    version = "b04213d2f4ca6079bef37491be07860baa8264b9";
    src = fetchgit {
      url = "https://github.com/AnirudhG07/custom-shell.yazi";
      rev = "b04213d2f4ca6079bef37491be07860baa8264b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hJVFZvcHgcjmcwUUGs1Q668KjeLSCEVuAhAD1A8ZM90=";
    };
    date = "2025-06-07";
  };
  mediainfo = {
    pname = "mediainfo";
    version = "f89605ce7ca33181ee6770e641d80ec4673093e0";
    src = fetchgit {
      url = "https://github.com/boydaihungst/mediainfo.yazi";
      rev = "f89605ce7ca33181ee6770e641d80ec4673093e0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NloChkZWKo9JL636d+G7vgEY/HX24udngYftw/Ydzk4=";
    };
    date = "2025-07-19";
  };
  office = {
    pname = "office";
    version = "4002d368c09841d5722d55720fd29c2eba05300f";
    src = fetchgit {
      url = "https://github.com/macydnah/office.yazi";
      rev = "4002d368c09841d5722d55720fd29c2eba05300f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XE+EfVPsO09zG8qYEhN6O95mS9NJlTdOd4Gsem2KtPI=";
    };
    date = "2025-06-02";
  };
  official-plugins-monorepo = {
    pname = "official-plugins-monorepo";
    version = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
    src = fetchgit {
      url = "https://github.com/yazi-rs/plugins";
      rev = "1ab21d43c7c6d326c1b9b06610ce7c8686257c43";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4p+VXUr76kC/dyJZzzkCwNGEUV53YYZ3tYoFpsKboU0=";
    };
    date = "2025-07-20";
  };
  other-monorepo = {
    pname = "other-monorepo";
    version = "ca18a2cfb893e3608997c9de54acced124373871";
    src = fetchgit {
      url = "https://github.com/lpanebr/yazi-plugins";
      rev = "ca18a2cfb893e3608997c9de54acced124373871";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v+EmMbrccAlzeR9rhmlFq0f+899l624EhWx1DFz+qzc=";
    };
    date = "2025-02-03";
  };
  ouch = {
    pname = "ouch";
    version = "0742fffea5229271164016bf96fb599d861972db";
    src = fetchgit {
      url = "https://github.com/ndtoan96/ouch.yazi";
      rev = "0742fffea5229271164016bf96fb599d861972db";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-C0wG8NQ+zjAMfd+J39Uvs3K4U6e3Qpo1yLPm2xcsAaI=";
    };
    date = "2025-07-13";
  };
  restore = {
    pname = "restore";
    version = "84f1921806c49b7b20af26cbe57cb4fd286142e2";
    src = fetchgit {
      url = "https://github.com/boydaihungst/restore.yazi";
      rev = "84f1921806c49b7b20af26cbe57cb4fd286142e2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pEQZ/2Z4XVYlfzqtCz51bIgE9KzkDF/qyX8vThhlWGI=";
    };
    date = "2025-07-11";
  };
  starship = {
    pname = "starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchgit {
      url = "https://github.com/Rolv-Apneseth/starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
  what-size = {
    pname = "what-size";
    version = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
    src = fetchgit {
      url = "https://github.com/pirafrank/what-size.yazi";
      rev = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s2BifzWr/uewDI6Bowy7J+5LrID6I6OFEA5BrlOPNcM=";
    };
    date = "2025-06-19";
  };
}
