# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  custom-shell = {
    pname = "custom-shell";
    version = "b04213d2f4ca6079bef37491be07860baa8264b9";
    src = fetchgit {
      url = "https://github.com/AnirudhG07/custom-shell.yazi";
      rev = "b04213d2f4ca6079bef37491be07860baa8264b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hJVFZvcHgcjmcwUUGs1Q668KjeLSCEVuAhAD1A8ZM90=";
    };
    date = "2025-06-07";
  };
  mediainfo = {
    pname = "mediainfo";
    version = "a15cdfac6bf23e53fc04a82bc15732257fc789aa";
    src = fetchgit {
      url = "https://github.com/boydaihungst/mediainfo.yazi";
      rev = "a15cdfac6bf23e53fc04a82bc15732257fc789aa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mvl45GaNaFxZntGJa+sZCrR0lDpHanxAE9FQPPpCMaY=";
    };
    date = "2025-06-19";
  };
  office = {
    pname = "office";
    version = "4002d368c09841d5722d55720fd29c2eba05300f";
    src = fetchgit {
      url = "https://github.com/macydnah/office.yazi";
      rev = "4002d368c09841d5722d55720fd29c2eba05300f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XE+EfVPsO09zG8qYEhN6O95mS9NJlTdOd4Gsem2KtPI=";
    };
    date = "2025-06-02";
  };
  official-plugins-monorepo = {
    pname = "official-plugins-monorepo";
    version = "7c174cc0ae1e07876218868e5e0917308201c081";
    src = fetchgit {
      url = "https://github.com/yazi-rs/plugins";
      rev = "7c174cc0ae1e07876218868e5e0917308201c081";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-RE93ZNlG6CRGZz7YByXtO0mifduh6MMGls6J9IYwaFA=";
    };
    date = "2025-06-26";
  };
  other-monorepo = {
    pname = "other-monorepo";
    version = "ca18a2cfb893e3608997c9de54acced124373871";
    src = fetchgit {
      url = "https://github.com/lpanebr/yazi-plugins";
      rev = "ca18a2cfb893e3608997c9de54acced124373871";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v+EmMbrccAlzeR9rhmlFq0f+899l624EhWx1DFz+qzc=";
    };
    date = "2025-02-03";
  };
  ouch = {
    pname = "ouch";
    version = "1ee69a56da3c4b90ec8716dd9dd6b82e7a944614";
    src = fetchgit {
      url = "https://github.com/ndtoan96/ouch.yazi";
      rev = "1ee69a56da3c4b90ec8716dd9dd6b82e7a944614";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4KZeDkMXlhUV0Zh+VGBtz9kFPGOWCexYVuKUSCN463o=";
    };
    date = "2025-06-11";
  };
  restore = {
    pname = "restore";
    version = "2c2802d8d2941dcf2c26bd07587de69e3589549c";
    src = fetchgit {
      url = "https://github.com/boydaihungst/restore.yazi";
      rev = "2c2802d8d2941dcf2c26bd07587de69e3589549c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-n/PNwyCOL3uCWgtSjq4+dPwr+hWSF4h9fbvZOQPBuYM=";
    };
    date = "2025-06-26";
  };
  starship = {
    pname = "starship";
    version = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
    src = fetchgit {
      url = "https://github.com/Rolv-Apneseth/starship.yazi";
      rev = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-q1G0Y4JAuAv8+zckImzbRvozVn489qiYVGFQbdCxC98=";
    };
    date = "2025-06-01";
  };
  what-size = {
    pname = "what-size";
    version = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
    src = fetchgit {
      url = "https://github.com/pirafrank/what-size.yazi";
      rev = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s2BifzWr/uewDI6Bowy7J+5LrID6I6OFEA5BrlOPNcM=";
    };
    date = "2025-06-19";
  };
  yamb = {
    pname = "yamb";
    version = "22af0033be18eead7b04c2768767d38ccfbaa05b";
    src = fetchgit {
      url = "https://github.com/h-hg/yamb.yazi";
      rev = "22af0033be18eead7b04c2768767d38ccfbaa05b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NMxZ8/7HQgs+BsZeH4nEglWsRH2ibAzq7hRSyrtFDTA=";
    };
    date = "2025-02-28";
  };
}
