# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  custom-shell = {
    pname = "custom-shell";
    version = "b04213d2f4ca6079bef37491be07860baa8264b9";
    src = fetchgit {
      url = "https://github.com/AnirudhG07/custom-shell.yazi";
      rev = "b04213d2f4ca6079bef37491be07860baa8264b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hJVFZvcHgcjmcwUUGs1Q668KjeLSCEVuAhAD1A8ZM90=";
    };
    date = "2025-06-07";
  };
  mediainfo = {
    pname = "mediainfo";
    version = "cc12f3f097cc57e41186697bd45d0e1598dc81ae";
    src = fetchgit {
      url = "https://github.com/boydaihungst/mediainfo.yazi";
      rev = "cc12f3f097cc57e41186697bd45d0e1598dc81ae";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-CTynpmB101ylCiHKbwX5nVrt5OMhgAu48GVxXsNqd9s=";
    };
    date = "2025-07-05";
  };
  office = {
    pname = "office";
    version = "4002d368c09841d5722d55720fd29c2eba05300f";
    src = fetchgit {
      url = "https://github.com/macydnah/office.yazi";
      rev = "4002d368c09841d5722d55720fd29c2eba05300f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XE+EfVPsO09zG8qYEhN6O95mS9NJlTdOd4Gsem2KtPI=";
    };
    date = "2025-06-02";
  };
  official-plugins-monorepo = {
    pname = "official-plugins-monorepo";
    version = "b8860253fc44e500edeb7a09db648a829084facd";
    src = fetchgit {
      url = "https://github.com/yazi-rs/plugins";
      rev = "b8860253fc44e500edeb7a09db648a829084facd";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-29K8PmBoqAMcQhDIfOVnbJt2FU4BR6k23Es9CqyEloo=";
    };
    date = "2025-07-06";
  };
  other-monorepo = {
    pname = "other-monorepo";
    version = "ca18a2cfb893e3608997c9de54acced124373871";
    src = fetchgit {
      url = "https://github.com/lpanebr/yazi-plugins";
      rev = "ca18a2cfb893e3608997c9de54acced124373871";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v+EmMbrccAlzeR9rhmlFq0f+899l624EhWx1DFz+qzc=";
    };
    date = "2025-02-03";
  };
  ouch = {
    pname = "ouch";
    version = "bb941c4891b21762f98318a6ad484827726019e6";
    src = fetchgit {
      url = "https://github.com/ndtoan96/ouch.yazi";
      rev = "bb941c4891b21762f98318a6ad484827726019e6";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-g/ZHArXksRo49k9UBHap0CXzIdycQigjbdCzDK1VaLY=";
    };
    date = "2025-07-07";
  };
  restore = {
    pname = "restore";
    version = "84f1921806c49b7b20af26cbe57cb4fd286142e2";
    src = fetchgit {
      url = "https://github.com/boydaihungst/restore.yazi";
      rev = "84f1921806c49b7b20af26cbe57cb4fd286142e2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-pEQZ/2Z4XVYlfzqtCz51bIgE9KzkDF/qyX8vThhlWGI=";
    };
    date = "2025-07-11";
  };
  starship = {
    pname = "starship";
    version = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
    src = fetchgit {
      url = "https://github.com/Rolv-Apneseth/starship.yazi";
      rev = "a63550b2f91f0553cc545fd8081a03810bc41bc0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-PYeR6fiWDbUMpJbTFSkM57FzmCbsB4W4IXXe25wLncg=";
    };
    date = "2025-07-08";
  };
  what-size = {
    pname = "what-size";
    version = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
    src = fetchgit {
      url = "https://github.com/pirafrank/what-size.yazi";
      rev = "d8966568f2a80394bf1f9a1ace6708ddd4cc8154";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-s2BifzWr/uewDI6Bowy7J+5LrID6I6OFEA5BrlOPNcM=";
    };
    date = "2025-06-19";
  };
  yamb = {
    pname = "yamb";
    version = "22af0033be18eead7b04c2768767d38ccfbaa05b";
    src = fetchgit {
      url = "https://github.com/h-hg/yamb.yazi";
      rev = "22af0033be18eead7b04c2768767d38ccfbaa05b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NMxZ8/7HQgs+BsZeH4nEglWsRH2ibAzq7hRSyrtFDTA=";
    };
    date = "2025-02-28";
  };
}
