[actually-all-emojis-spaces]
fetch.git = "https://github.com/jobiewong/espanso-emojis"
src.git = "https://github.com/jobiewong/espanso-emojis"

[lower-upper]
fetch.git = "https://github.com/anthonygraignic/espanso-package-lower-upper"
src.git = "https://github.com/anthonygraignic/espanso-package-lower-upper"

[mega-pack]
fetch.git = "https://github.com/jpmvferreira/espanso-mega-pack"
src.git = "https://github.com/jpmvferreira/espanso-mega-pack"
