[dunefetch]
fetch.git = "https://github.com/datavorous/dunefetch"
src.git = "https://github.com/datavorous/dunefetch"

[watershot]
fetch.git = "https://github.com/Kirottu/watershot"
src.git = "https://github.com/Kirottu/watershot"

[xdg-desktop-portal-termfilechooser]
fetch.git = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser"
src.git = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser"
