# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ns = {
    pname = "ns";
    version = "latest";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/Vortriz/nix-search-tv/refs/heads/main/nixpkgs.sh";
      name = "nixpkgs.sh";
      sha256 = "sha256-bD769ysDjt6KhIpLTrEDS+BP9rq4Nen2v4hKMemBMDs=";
    };
  };
  starship-nerd-font-symbols = {
    pname = "starship-nerd-font-symbols";
    version = "latest";
    src = fetchurl {
      url = "https://starship.rs/presets/toml/nerd-font-symbols.toml";
      name = "nerd-font-symbols.toml";
      sha256 = "sha256-MtAuCwg+6Ol0owyXrp1a+RtfKpSEBI68dikD95xmP/M=";
    };
  };
}
