# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  actually-all-emojis-spaces = {
    pname = "actually-all-emojis-spaces";
    version = "88ba2b715edaef0ce26238684edc62221d9a7c67";
    src = fetchgit {
      url = "https://github.com/jobiewong/espanso-emojis";
      rev = "88ba2b715edaef0ce26238684edc62221d9a7c67";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SUNktVuCLOAWWWtn+pOz31RtdtN3ONXn5iCBhKj4oUA=";
    };
    date = "2023-06-22";
  };
  lower-upper = {
    pname = "lower-upper";
    version = "9ed3737f0a6605d3d9b607eefc82efdf5e746859";
    src = fetchgit {
      url = "https://github.com/anthonygraignic/espanso-package-lower-upper";
      rev = "9ed3737f0a6605d3d9b607eefc82efdf5e746859";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7ZVtI0DILjsV8cKCdIr8Z3ZjkorfL9mKoxO0Qra02G4=";
    };
    date = "2021-11-04";
  };
  mega-pack = {
    pname = "mega-pack";
    version = "abb8e9f8baaf3196e876f2c54b246e2fabe42947";
    src = fetchgit {
      url = "https://github.com/jpmvferreira/espanso-mega-pack";
      rev = "abb8e9f8baaf3196e876f2c54b246e2fabe42947";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lIEb6yGWdBy21U0Lw19Hfm5gY3ZfUoUqh++VtfsV9dI=";
    };
    date = "2025-06-25";
  };
  ns = {
    pname = "ns";
    version = "latest";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/Vortriz/nix-search-tv/refs/heads/main/nixpkgs.sh";
      name = "nixpkgs.sh";
      sha256 = "sha256-IpVah9sYcapDEfOCm7zloHW1NpK6stZD7/7TDPbrkJs=";
    };
  };
  shyfox = {
    pname = "shyfox";
    version = "de69fb6b272cf4a0b4044fc02fe27286eb4675a0";
    src = fetchgit {
      url = "https://github.com/Vortriz/ShyFox";
      rev = "de69fb6b272cf4a0b4044fc02fe27286eb4675a0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-alrK8s1B+ShX4yda27jPPvBZTIE0nYu9iQYAmtzQrZc=";
    };
    date = "2025-09-29";
  };
  starship-nerd-font-symbols = {
    pname = "starship-nerd-font-symbols";
    version = "latest";
    src = fetchurl {
      url = "https://starship.rs/presets/toml/nerd-font-symbols.toml";
      name = "nerd-font-symbols.toml";
      sha256 = "sha256-KssAxwGVYGGBMcH6Lwq1sllYwqrD95TfpcjydMtCceM=";
    };
  };
  zotero-better-bibtex = {
    pname = "zotero-better-bibtex";
    version = "7.0.68";
    src = fetchurl {
      url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v7.0.68/zotero-better-bibtex-7.0.68.xpi";
      sha256 = "sha256-Nr6tSqeMqvmMl52crlPTegyquVbT1Y6nnve+muvEKT8=";
    };
    addonId = "better-bibtex@iris-advies.com";
    license = "mit";
    homepage = "https://github.com/retorquere/zotero-better-bibtex";
    description = "Make Zotero effective for us LaTeX holdouts";
  };
  zotero-scipdf = {
    pname = "zotero-scipdf";
    version = "1.3.0";
    src = fetchurl {
      url = "https://github.com/syt2/zotero-scipdf/releases/download/V1.3.0/sci-pdf.xpi";
      sha256 = "sha256-Z0OVtN7JHmvfE0hZ6rQ6VUgLFJPF3hnewJn/iQ+Ma8c=";
    };
    addonId = "scipdf@ytshen.com";
    license = "agpl3Plus";
    homepage = "https://github.com/syt2/zotero-scipdf";
    description = "Download PDF from Sci-Hub automatically (For Zotero7)";
  };
  zotero-zotmoov = {
    pname = "zotero-zotmoov";
    version = "1.2.25";
    src = fetchurl {
      url = "https://github.com/wileyyugioh/zotmoov/releases/download/1.2.25/zotmoov-1.2.25-fx.xpi";
      sha256 = "sha256-WnmKB5bR09KpR8KuLCK6rC8Ur2n6+Uw26CaeNzJUj1g=";
    };
    addonId = "zotmoov@wileyy.com";
    license = "gpl3Only";
    homepage = "https://github.com/wileyyugioh/zotmoov";
    description = "Mooves attachments and links them";
  };
}
