# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  dgop = {
    pname = "dgop";
    version = "ea31f32db1c7ed1905b98eaaa0f3fd8d9afb36fc";
    src = fetchgit {
      url = "https://github.com/AvengeMedia/dgop";
      rev = "ea31f32db1c7ed1905b98eaaa0f3fd8d9afb36fc";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-QCJbcczQjUZ+Xf7tQHckuP9h8SD0C4p0C8SVByIAq/g=";
    };
    date = "2025-08-11";
  };
  dunefetch = {
    pname = "dunefetch";
    version = "7adfd33406a556b7d096f11dc446570c81b17675";
    src = fetchgit {
      url = "https://github.com/datavorous/dunefetch";
      rev = "7adfd33406a556b7d096f11dc446570c81b17675";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-x6VlBa6qgwKyg8JxTCl6Y9rSzFk/8gaj2lanTZvl6XM=";
    };
    date = "2025-08-12";
  };
  xdg-desktop-portal-termfilechooser = {
    pname = "xdg-desktop-portal-termfilechooser";
    version = "8217ad28bfd05c9bf8242cc357f36da0119a860a";
    src = fetchgit {
      url = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser";
      rev = "8217ad28bfd05c9bf8242cc357f36da0119a860a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-60gb23OCYBNCx9fLVGzmkuIaKgA1UxIypAHod9xKFIA=";
    };
    date = "2025-08-01";
  };
}
