# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-desktop-portal-termfilechooser = {
    pname = "xdg-desktop-portal-termfilechooser";
    version = "a100380baa3876bd3955b831dbacee952ea70f30";
    src = fetchgit {
      url = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser";
      rev = "a100380baa3876bd3955b831dbacee952ea70f30";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-82ntBM2n8Mv2CL107eY7jySYKMdGhb8+1HoSe2eF0Fc=";
    };
    date = "2025-06-18";
  };
}
