# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  xdg-desktop-portal-termfilechooser = {
    pname = "xdg-desktop-portal-termfilechooser";
    version = "ac37f0dd12212c306c2f70a459f7fe4b276e5494";
    src = fetchgit {
      url = "https://github.com/hunkyburrito/xdg-desktop-portal-termfilechooser";
      rev = "ac37f0dd12212c306c2f70a459f7fe4b276e5494";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-aqFaf87f0Th9MRzLthCnTuw41R2B5z0hx7dAaZ/KEWo=";
    };
    date = "2025-07-01";
  };
}
