[zotero-better-bibtex]
fetch.url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v$ver/zotero-better-bibtex-$ver.xpi"

[zotero-better-bibtex.passthru]
addonId = "better-bibtex@iris-advies.com"
description = "Make Zotero effective for us LaTeX holdouts"
homepage = "https://github.com/retorquere/zotero-better-bibtex"
license = "mit"
src.github_tag = "retorquere/zotero-better-bibtex"
src.prefix = "v"
src.exclude_regex = "v6.7.267"

[zotero-scipdf]
fetch.url = "https://github.com/syt2/zotero-scipdf/releases/download/V$ver/sci-pdf.xpi"

[zotero-scipdf.passthru]
addonId = "scipdf@ytshen.com"
description = "Download PDF from Sci-Hub automatically (For Zotero7)"
homepage = "https://github.com/syt2/zotero-scipdf"
license = "agpl3Plus"
src.github = "syt2/zotero-scipdf"
src.prefix = "V"

[zotero-zotmoov]
fetch.url = "https://github.com/wileyyugioh/zotmoov/releases/download/$ver/zotmoov-$ver-fx.xpi"

[zotero-zotmoov.passthru]
addonId = "zotmoov@wileyy.com"
description = "Mooves attachments and links them"
homepage = "https://github.com/wileyyugioh/zotmoov"
license = "gpl3Only"
src.github = "wileyyugioh/zotmoov"
