app_launch_prefix = ""
as_window = false
close_when_open = false
disable_click_to_close = false
force_keyboard_focus = false
hotreload_theme = true
locale = ""
monitor = ""
terminal_title_flag = ""
theme = "nixos"
timeout = 0
[activation_mode]
labels = ""

[builtins.ai]
hidden = true

[builtins.applications]
context_aware = true
hide_actions_with_empty_query = true
history = true
name = "applications"
placeholder = "Applications"
prioritize_new = true
refresh = true
show_generic = true
show_icon_when_single = true
show_sub_when_single = true
weight = 5
[builtins.applications.actions]
enabled = true
hide_category = false
hide_without_query = true

[builtins.bookmarks]
hidden = true

[builtins.calc]
icon = "accessories-calculator"
min_chars = 4
name = "calc"
placeholder = "Calculator"
require_number = true
weight = 5

[builtins.clipboard]
hidden = true

[builtins.commands]
icon = "utilities-terminal"
name = "commands"
placeholder = "Commands"
switcher_only = true
weight = 5

[builtins.custom_commands]
icon = "utilities-terminal"
name = "custom_commands"
placeholder = "Custom Commands"
weight = 5
[[builtins.custom_commands.commands]]
cmd = "kitty"
name = "kitty"
terminal = true

[builtins.dmenu]
hidden = true

[builtins.emojis]
exec = "wl-copy"
history = true
name = "emojis"
placeholder = "Emojis"
show_unqualified = false
switcher_only = true
typeahead = true
weight = 5

[builtins.finder]
concurrency = 8
fd_flags = "--ignore-vcs --type directory --base-directory /mnt/HOUSE/"
icon = "file"
ignore_gitignore = true
name = "finder"
placeholder = "Finder"
preview_images = false
refresh = true
show_icon_when_single = true
switcher_only = false
use_fd = true
weight = 5

[builtins.runner]
eager_loading = true
generic_entry = false
history = true
icon = "utilities-terminal"
name = "runner"
placeholder = "Runner"
refresh = true
typeahead = true
use_fd = false
weight = 5

[builtins.ssh]
hidden = true

[builtins.switcher]
name = "switcher"
placeholder = "Switcher"
prefix = "/"
weight = 5

[builtins.symbols]
hidden = true

[builtins.translation]
hidden = true

[builtins.websearch]
icon = "applications-internet"
keep_selection = true
name = "websearch"
placeholder = "Websearch"
weight = 5
[[builtins.websearch.entries]]
name = "Google"
prefix = "g "
url = "https://www.google.com/search?q=%TERM%"

[builtins.windows]
hidden = true

[builtins.xdph_picker]
hidden = true

[events]
on_activate = ""
on_exit = ""
on_launch = ""
on_query_change = ""
on_selection = ""

[keys]
accept_typeahead = ["tab"]
close = ["esc"]
next = ["down"]
prev = ["up"]
remove_from_history = ["shift backspace"]
resume_query = ["ctrl r"]
toggle_exact_search = ["ctrl m"]
trigger_labels = "lalt"

[keys.activation_modifiers]
alternate = "alt"
keep_open = "shift"

[keys.ai]
clear_session = ["ctrl x"]
copy_last_response = ["ctrl c"]
resume_session = ["ctrl r"]
run_last_response = ["ctrl e"]

[list]
dynamic_sub = true
keyboard_scroll_style = "emacs"
max_entries = 50
placeholder = "No Results"
show_initial_entries = true
single_click = true
visibility_threshold = 20

[search]
argument_delimiter = "#"
delay = 0
placeholder = "Search..."
resume_last_query = false
