{
    imports = [
        ./firefox
        ./download-manager.nix
        ./file-managers.nix
        ./file-transfer.nix
        ./image-editor.nix
        ./image-viewer.nix
        ./music.nix
        ./obsidian.nix
        ./office-suite.nix
        ./pdf-viewer.nix
        ./remote-desktop.nix
        ./social-apps.nix
        ./system-monitor.nix
        ./torrent.nix
        ./utilities.nix
        ./video-player.nix
        ./vscode.nix
    ];
}