# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  actually-all-emojis-spaces = {
    pname = "actually-all-emojis-spaces";
    version = "88ba2b715edaef0ce26238684edc62221d9a7c67";
    src = fetchgit {
      url = "https://github.com/jobiewong/espanso-emojis";
      rev = "88ba2b715edaef0ce26238684edc62221d9a7c67";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-SUNktVuCLOAWWWtn+pOz31RtdtN3ONXn5iCBhKj4oUA=";
    };
    date = "2023-06-22";
  };
  lower-upper = {
    pname = "lower-upper";
    version = "9ed3737f0a6605d3d9b607eefc82efdf5e746859";
    src = fetchgit {
      url = "https://github.com/anthonygraignic/espanso-package-lower-upper";
      rev = "9ed3737f0a6605d3d9b607eefc82efdf5e746859";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-7ZVtI0DILjsV8cKCdIr8Z3ZjkorfL9mKoxO0Qra02G4=";
    };
    date = "2021-11-04";
  };
  mega-pack = {
    pname = "mega-pack";
    version = "abb8e9f8baaf3196e876f2c54b246e2fabe42947";
    src = fetchgit {
      url = "https://github.com/jpmvferreira/espanso-mega-pack";
      rev = "abb8e9f8baaf3196e876f2c54b246e2fabe42947";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-lIEb6yGWdBy21U0Lw19Hfm5gY3ZfUoUqh++VtfsV9dI=";
    };
    date = "2025-06-25";
  };
}
