# This file was generated by nvfetcher, please do not modify it manually.
{fetchurl}: {
    zotero-better-bibtex = {
        pname = "zotero-better-bibtex";
        version = "7.0.35";
        src = fetchurl {
            url = "https://github.com/retorquere/zotero-better-bibtex/releases/download/v7.0.35/zotero-better-bibtex-7.0.35.xpi";
            sha256 = "sha256-wL2fyUnOQ3p9RiZFc/ZtMMN+xrgre6hl7/ntVChMlzo=";
        };
        addonId = "better-bibtex@iris-advies.com";
        license = "mit";
        homepage = "https://github.com/retorquere/zotero-better-bibtex";
        description = "Make Zotero effective for us LaTeX holdouts";
    };
    zotero-scipdf = {
        pname = "zotero-scipdf";
        version = "1.3.0";
        src = fetchurl {
            url = "https://github.com/syt2/zotero-scipdf/releases/download/V1.3.0/sci-pdf.xpi";
            sha256 = "sha256-Z0OVtN7JHmvfE0hZ6rQ6VUgLFJPF3hnewJn/iQ+Ma8c=";
        };
        addonId = "scipdf@ytshen.com";
        license = "agpl3Plus";
        homepage = "https://github.com/syt2/zotero-scipdf";
        description = "Download PDF from Sci-Hub automatically (For Zotero7)";
    };
    zotero-zotmoov = {
        pname = "zotero-zotmoov";
        version = "1.2.21";
        src = fetchurl {
            url = "https://github.com/wileyyugioh/zotmoov/releases/download/1.2.21/zotmoov-1.2.21-fx.xpi";
            sha256 = "sha256-gN5INdWAM8LSJKGzinklT05x4oU28muJUYLtmmh9Pn4=";
        };
        addonId = "zotmoov@wileyy.com";
        license = "gpl3Only";
        homepage = "https://github.com/wileyyugioh/zotmoov";
        description = "Mooves attachments and links them";
    };
}
