# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  custom-shell = {
    pname = "custom-shell";
    version = "b04213d2f4ca6079bef37491be07860baa8264b9";
    src = fetchgit {
      url = "https://github.com/AnirudhG07/custom-shell.yazi";
      rev = "b04213d2f4ca6079bef37491be07860baa8264b9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hJVFZvcHgcjmcwUUGs1Q668KjeLSCEVuAhAD1A8ZM90=";
    };
    date = "2025-06-07";
  };
  mediainfo = {
    pname = "mediainfo";
    version = "a7d1aa69a1a107e64540c17f19ac94be1366769f";
    src = fetchgit {
      url = "https://github.com/boydaihungst/mediainfo.yazi";
      rev = "a7d1aa69a1a107e64540c17f19ac94be1366769f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-HUD8Sv1C4gzZRvSEIYqcmm+A0mBYDuwZHCNH26kipS0=";
    };
    date = "2025-06-05";
  };
  office = {
    pname = "office";
    version = "4002d368c09841d5722d55720fd29c2eba05300f";
    src = fetchgit {
      url = "https://github.com/macydnah/office.yazi";
      rev = "4002d368c09841d5722d55720fd29c2eba05300f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-XE+EfVPsO09zG8qYEhN6O95mS9NJlTdOd4Gsem2KtPI=";
    };
    date = "2025-06-02";
  };
  official-plugins-monorepo = {
    pname = "official-plugins-monorepo";
    version = "63f9650e522336e0010261dcd0ffb0bf114cf912";
    src = fetchgit {
      url = "https://github.com/yazi-rs/plugins";
      rev = "63f9650e522336e0010261dcd0ffb0bf114cf912";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ZCLJ6BjMAj64/zM606qxnmzl2la4dvO/F5QFicBEYfU=";
    };
    date = "2025-05-31";
  };
  other-monorepo = {
    pname = "other-monorepo";
    version = "ca18a2cfb893e3608997c9de54acced124373871";
    src = fetchgit {
      url = "https://github.com/lpanebr/yazi-plugins";
      rev = "ca18a2cfb893e3608997c9de54acced124373871";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v+EmMbrccAlzeR9rhmlFq0f+899l624EhWx1DFz+qzc=";
    };
    date = "2025-02-03";
  };
  ouch = {
    pname = "ouch";
    version = "10b462765f37502065555e83c68a72bb26870fe2";
    src = fetchgit {
      url = "https://github.com/ndtoan96/ouch.yazi";
      rev = "10b462765f37502065555e83c68a72bb26870fe2";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-mtXl76a54Deg4cyrD0wr++sD/5b/kCsnJ+ngM6OokTc=";
    };
    date = "2025-06-02";
  };
  restore = {
    pname = "restore";
    version = "b7c33766e0bc4bbbb99e8e934be90e3beb881d29";
    src = fetchgit {
      url = "https://github.com/boydaihungst/restore.yazi";
      rev = "b7c33766e0bc4bbbb99e8e934be90e3beb881d29";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qtthY7eySqXoA3TARubZF0SsYkkLEgkjdtPUxR5ro0I=";
    };
    date = "2025-06-05";
  };
  starship = {
    pname = "starship";
    version = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
    src = fetchgit {
      url = "https://github.com/Rolv-Apneseth/starship.yazi";
      rev = "6a0f3f788971b155cbc7cec47f6f11aebbc148c9";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-q1G0Y4JAuAv8+zckImzbRvozVn489qiYVGFQbdCxC98=";
    };
    date = "2025-06-01";
  };
  what-size = {
    pname = "what-size";
    version = "0a4904cf4f8f14d36fe72976d9b6b7597cd303ee";
    src = fetchgit {
      url = "https://github.com/pirafrank/what-size.yazi";
      rev = "0a4904cf4f8f14d36fe72976d9b6b7597cd303ee";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-3prRpFuz1ZjPkpl1h4WCL7HY7XhIWGU5hg1E8bG/8f0=";
    };
    date = "2025-05-28";
  };
  yamb = {
    pname = "yamb";
    version = "22af0033be18eead7b04c2768767d38ccfbaa05b";
    src = fetchgit {
      url = "https://github.com/h-hg/yamb.yazi";
      rev = "22af0033be18eead7b04c2768767d38ccfbaa05b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NMxZ8/7HQgs+BsZeH4nEglWsRH2ibAzq7hRSyrtFDTA=";
    };
    date = "2025-02-28";
  };
}
