# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  auto-layout = {
    pname = "auto-layout";
    version = "626a6016283558b9766fe305e76b694dd9fb6156";
    src = fetchgit {
      url = "https://github.com/josephschmitt/auto-layout.yazi";
      rev = "626a6016283558b9766fe305e76b694dd9fb6156";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-sGyy1tLDqR1aNrxQBHcswqussorIkQX70rsR2JoC1Lo=";
    };
    date = "2025-03-07";
  };
  custom-shell = {
    pname = "custom-shell";
    version = "6b4550a1b18afbb7ef328ebf54d81de24101288e";
    src = fetchgit {
      url = "https://github.com/AnirudhG07/custom-shell.yazi";
      rev = "6b4550a1b18afbb7ef328ebf54d81de24101288e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-deLbUM4J/pDrLdKeEp62GJ+CFdwsSwOUiX85KuCRStc=";
    };
    date = "2025-02-10";
  };
  glow = {
    pname = "glow";
    version = "2da96e3ffd9cd9d4dd53e0b2636f83ff69fe9af0";
    src = fetchgit {
      url = "https://github.com/Reledia/glow.yazi";
      rev = "2da96e3ffd9cd9d4dd53e0b2636f83ff69fe9af0";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-4krck4U/KWmnl32HWRsblYW/biuqzDPysrEn76buRck=";
    };
    date = "2025-04-15";
  };
  mediainfo = {
    pname = "mediainfo";
    version = "9629b1e85c3757c834ec83fb7d931982c55f4c3f";
    src = fetchgit {
      url = "https://github.com/boydaihungst/mediainfo.yazi";
      rev = "9629b1e85c3757c834ec83fb7d931982c55f4c3f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-EDEIiZJy/RfXVaLNsKDeklH4qY2h+js2m0y6VSAjPkk=";
    };
    date = "2025-04-17";
  };
  office = {
    pname = "office";
    version = "d1e3e51857c109fbfc707ab0f9f383dc98b9795f";
    src = fetchgit {
      url = "https://github.com/macydnah/office.yazi";
      rev = "d1e3e51857c109fbfc707ab0f9f383dc98b9795f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ORcexu1f7hb7G4IyzQIfGlCkH3OWlk4w5FtZrbXkR40=";
    };
    date = "2025-04-26";
  };
  official-plugins-monorepo = {
    pname = "official-plugins-monorepo";
    version = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
    src = fetchgit {
      url = "https://github.com/yazi-rs/plugins";
      rev = "55bf6996ada3df4cbad331ce3be0c1090769fc7c";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v/C+ZBrF1ghDt1SXpZcDELmHMVAqfr44iWxzUWynyRk=";
    };
    date = "2025-05-11";
  };
  other-monorepo = {
    pname = "other-monorepo";
    version = "ca18a2cfb893e3608997c9de54acced124373871";
    src = fetchgit {
      url = "https://github.com/lpanebr/yazi-plugins";
      rev = "ca18a2cfb893e3608997c9de54acced124373871";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-v+EmMbrccAlzeR9rhmlFq0f+899l624EhWx1DFz+qzc=";
    };
    date = "2025-02-03";
  };
  ouch = {
    pname = "ouch";
    version = "2496cd9ac2d1fb52597b22ae84f3af06c826a86d";
    src = fetchgit {
      url = "https://github.com/ndtoan96/ouch.yazi";
      rev = "2496cd9ac2d1fb52597b22ae84f3af06c826a86d";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-OsNfR7rtnq+ceBTiFjbz+NFMSV/6cQ1THxEFzI4oPJk=";
    };
    date = "2025-04-12";
  };
  restore = {
    pname = "restore";
    version = "539aad5077dc8b342a580036e416f2b949b6590e";
    src = fetchgit {
      url = "https://github.com/boydaihungst/restore.yazi";
      rev = "539aad5077dc8b342a580036e416f2b949b6590e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-ngwbweKF7pSEpzy1TNzbKz8cFIWaDison5vCiGxkHFk=";
    };
    date = "2025-04-25";
  };
  what-size = {
    pname = "what-size";
    version = "f1c6b691363e602d0ddbee29384017d08b608f64";
    src = fetchgit {
      url = "https://github.com/pirafrank/what-size.yazi";
      rev = "f1c6b691363e602d0ddbee29384017d08b608f64";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-M1phqmo318/VYkLWiqjEWuHlnQ+hfz5H+k8G0zsmclg=";
    };
    date = "2025-04-07";
  };
  yamb = {
    pname = "yamb";
    version = "22af0033be18eead7b04c2768767d38ccfbaa05b";
    src = fetchgit {
      url = "https://github.com/h-hg/yamb.yazi";
      rev = "22af0033be18eead7b04c2768767d38ccfbaa05b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-NMxZ8/7HQgs+BsZeH4nEglWsRH2ibAzq7hRSyrtFDTA=";
    };
    date = "2025-02-28";
  };
}
