[auto-layout]
fetch.git = "https://github.com/josephschmitt/auto-layout.yazi"
src.git = "https://github.com/josephschmitt/auto-layout.yazi"

[custom-shell]
fetch.git = "https://github.com/AnirudhG07/custom-shell.yazi"
src.git = "https://github.com/AnirudhG07/custom-shell.yazi"

[glow]
fetch.git = "https://github.com/Reledia/glow.yazi"
src.git = "https://github.com/Reledia/glow.yazi"

[mediainfo]
fetch.git = "https://github.com/boydaihungst/mediainfo.yazi"
src.git = "https://github.com/boydaihungst/mediainfo.yazi"

[office]
fetch.git = "https://github.com/macydnah/office.yazi"
src.git = "https://github.com/macydnah/office.yazi"

[official-plugins-monorepo]
fetch.git = "https://github.com/yazi-rs/plugins"
src.git = "https://github.com/yazi-rs/plugins"

[other-monorepo]
fetch.git = "https://github.com/lpanebr/yazi-plugins"
src.git = "https://github.com/lpanebr/yazi-plugins"

[ouch]
fetch.git = "https://github.com/ndtoan96/ouch.yazi"
src.git = "https://github.com/ndtoan96/ouch.yazi"

[restore]
fetch.git = "https://github.com/boydaihungst/restore.yazi"
src.git = "https://github.com/boydaihungst/restore.yazi"

[what-size]
fetch.git = "https://github.com/Vortriz/what-size.yazi"
src.git = "https://github.com/Vortriz/what-size.yazi"

[yamb]
fetch.git = "https://github.com/h-hg/yamb.yazi"
src.git = "https://github.com/h-hg/yamb.yazi"
