# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ns = {
    pname = "ns";
    version = "19adb1f1fe0815721d54f7cf0c68663b7696ef3a";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/Vortriz/nix-search-tv/refs/heads/main/nixpkgs.sh";
      sha256 = "sha256-VMfQFvvgAw8b58GA8H53K08wKv1Q0GsUKmgLJbTARDI=";
    };
    date = "2025-10-31";
  };
}
