# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  ns = {
    pname = "ns";
    version = "5f8efd655b537790f5b5a109fcd0f67531ebd4a5";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/Vortriz/nix-search-tv/refs/heads/main/nixpkgs.sh";
      sha256 = "sha256-VMfQFvvgAw8b58GA8H53K08wKv1Q0GsUKmgLJbTARDI=";
    };
    date = "2025-10-23";
  };
}
