{
    config,
    lib,
    ...
}:
with lib; let
    cfg = config.programs.nix-search-tv;
in {
    options.programs.nix-search-tv = {
        enable = mkEnableOption "Enable nix-search-tv";

        package = mkOption {
            type = types.package;
            description = "nix-search-tv package to use";
        };

        config = mkOption {
            type = types.lines;
            default = "";
            description = "`config.json` as per https://github.com/3timeslazy/nix-search-tv?tab=readme-ov-file#configuration";
        };
    };

    config = mkIf cfg.enable {
        home.packages = [cfg.package];

        xdg.configFile."nix-search-tv/config.json" = mkIf (cfg.config != "") {
            text = ''
                # Generated by Home Manager.
                ${cfg.extraConfig}
            '';
        };
    };
}
